services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GENAI_API_KEY=${GENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=${REDIS_URL}
    networks:
      - app-network
    # restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://backend.ifobito.online
    networks:
      - app-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_chatbot
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
